import pygame
from script import load_image
player_image = load_image('image/player')
earth_image = pygame.image.load('image/blocks/earth.png')
center_image = pygame.image.load('image/blocks/center.png')
water_image = pygame.image.load('image/blocks/water.png')
box_image = pygame.image.load('image/blocks/box.png')
stop_image = pygame.image.load('image/blocks/stop (1).png')
enemy_1_image =load_image('image/enemy/1')
enemy_2_image = load_image('image/enemy/2')
enemy_3_image = load_image('image/enemy/3')
enemy_4_image = load_image('image/enemy/4')
portal_image = pygame.image.load('image/portal/Portal_100x100px1.png')
monetka_image = pygame.image.load('image/item/monetka.png')
fireball_image = load_image('image/fireball')